index.js
package.json

Should fix https://github.com/vladikoff/node-geckodriver/issues/6#issuecomment-241815139 (which I also experienced).

Implement archive extraction on Windows

---

index.js

I was getting a weird error running selenium on my windows VM, then I realised that geckodriver was a 64-bit executable running on my 32-bit OS (I tend to do that when the VM needs less than 4gb ram).
Mozilla release 32-bit versions of both linux and windows drivers, so it makes sense to download the correct one?
I've only actually tested the 32-bit codepath on windows but I did check the linux32 tarball had the right filename inside it. I also noted that nodejs has multiple 32-bit arch values but only one 64-bit so I structured the check to use 32-bit as a fallback if the arch isn't 64-bit.

Support for 32-bit windows and linux builds

---

README.md
index.js

This PR adds a configuration option called `GECKODRIVER_CDNURL`, which is similar to the option `CHROMEDRIVER_CDNURL` in the `chromedriver` project.
Currently, when installing `geckodriver` on CI machines in a restricted corporate network such as the one we have at Walmart, `geckodriver` binary installation fails due to the assumption that github access is available.
This PR adds:
- Code which either uses the default or `GECKODRIVER_CDNURL` if present, with trailing slash stripping (similar to `chromedriver`'s convention).
- Update to README on how to configure the CDN option, what it's for, and where to place binaries on a CDN relative to the base URL.
/cc @vladikoff

Add support for a binary CDN location

---

package.json

On Windows, as on other platforms, this package installs the ./bin/geckodriver script to a directory in PATH (which then runs the geckodriver.exe executable that gets downloaded to the package's directory). But the selenium-webdriver package expects to find a geckodriver.exe executable in the PATH on Windows:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/firefox/index.js#L296-L297
So it can't find the executable after I install it via this package.
This pull request is a hack that directs npm to install ./bin/geckodriver as geckodriver.exe as well. I'm not happy with this approach, since it happens on all three platforms rather than only on Windows. But it does solve the problem (and shouldn't cause problems on Mac/Linux).
An alternative might be to …

add bin target w/.exe extension

---

README.md
package.json

As I mentioned in #31, the fix for #29 didn't really solve the problem, and it doesn't look like there's an actual solution that doesn't itself cause more problems. So this branch reverts #29 and then documents how to manually link geckodriver.exe into your PATH on Windows.
Sorry for the churn. 😞

document how to link geckodriver.exe manually

---

index.js

This allows for usage of things such as basic auth, and other features
that node's built-in url library support that `got` expects.
I only tested this by installing node-geckodriver via
```
GECKODRIVER_CDNURL="https://${ght}@github.com/mozilla/geckodriver/releases/download" npm link ../node-geckodriver/
```
and confirmed that it no longer threw the error present in the upstream
issue sindresorhus/got#184
```
Error: Basic authentication must be done with auth option                                                                                                      │$: git co master
at normalizeArguments (~/code/project/node_modules/got/index.js:215:10)
```

fix(url): Pass parsed url to got

---

index.js

Another option to support for a binary CDN location.

Add support for a binary CDN location by npm config

---

package.json

adm-zip npm library before 0.4.11 is vulnerable to directory traversal, allowing attackers to write to arbitrary file...
https://nvd.nist.gov/vuln/detail/CVE-2018-1002204

Update adm-zip package version to 0.4.11

---

README.md
index.js
lib/geckodriver.js

Some of us are unfortunately in a corporate environment that locks down the version of applications. 
This PR adds the ability to specify via an environment variable which version of geckodriver to install. This method is similar to the method [chromedriver ](https://github.com/giggio/node-chromedriver/blob/master/install.js#L27) uses.

feat: support fixed version of geckodriver

---

README.md
index.js

We'd like to cache a version of the geckodriver archive because we've seen a number of failed postinstall script runs. Chromedriver supports this with the `CHROMEDRIVER_FILEPATH` environment flag, I was thinking it would make sense to add a `GECKODRIVER_FILEPATH` that points to the relevant filepath.

Allow specifying GECKODRIVER_FILEPATH

---

package.json

https://www.npmjs.com/advisories/803
The version of `tar` in use has a security issue and thus fails `npm audit`.
This PR addresses that.

Upgrade tar dependency

---

README.md
index.js

Aligns behaviour with [chromedriver](https://github.com/giggio/node-chromedriver/blob/master/install.js#L13-L17). Needed for protected build environments where neither an official mirror is reachable nor a dedicated CDN is available.

skip geckodriver download

---

index.js
lib/geckodriver.js
test/index.js

New geckodriver 0.25.0 is [available](https://github.com/mozilla/geckodriver/releases/tag/v0.25.0). 
I tested it with Firefox 69.0.1 on Mac and do not see any issues.
@vladikoff I guess it should be under 1.17.x release?

update default driver version to 0.25.0

---

index.js
lib/geckodriver.js
package-lock.json
package.json
test/index.js

New geckodriver v [0.26.0](https://github.com/mozilla/geckodriver/releases/tag/v0.26.0) was released.
Tested on MacOS 10.14.6

update geckodriver to 0.26

---

index.js

In some environment, it use `https_proxy` and `http_proxy` instead.
In this case, it will fail in the download process.

fix: Update proxy

---

README.md
index.js
lib/geckodriver.js
package-lock.json
package.json

[0.28.0](https://github.com/mozilla/geckodriver/releases/tag/v0.28.0) was recently released

Bumb default geckodriver version

---

README.md
index.js
lib/geckodriver.js
package.json
test/index.js

Adding the latest [0.29.0](https://github.com/mozilla/geckodriver/releases/tag/v0.29.0) release

bump default binary to 0.29.0

---

package-lock.json
package.json

Version 0.4.16 of apm-zip had a security vulnerability, see: https://app.snyk.io/vuln/SNYK-JS-ADMZIP-1065796

Bump adm-zip from 0.4.16 to 0.5.3

---

index.js

Some explanation about why it would work in case you're confused by Got's document
In Got's readme it gives two example about setting proxy.
- using "tunnel"
`
await got('https://sindresorhus.com', {
agent: {
https: tunnel.httpsOverHttp({
proxy: {
host: 'localhost'
}
})
}
});
`
- or hpagent
`
await got('https://sindresorhus.com', {
agent: {
https: new HttpsProxyAgent({
keepAlive: true,
keepAliveMsecs: 1000,
maxSockets: 256,
maxFreeSockets: 256,
scheduling: 'lifo',
proxy: 'https://localhost:8080'
})
}
});
`
But meanwhile if you check the ["agent"](https://github.com/sindresorhus/got#agent) chapter
it says
```md
agent
Type: object
An object representing http, https and http2 keys for **http.Agent, https.Agent** and http2wrapper.Agent **instance**.
```
So the current proxy agent …

fix post install script about execution error in proxy environment

---

src/index.ts

This non-relative import breaks some of the more strict type-checking systems :)
e.g.,:
```
build-system/tasks/e2e/node_modules/geckodriver/dist/index.d.ts:4:44 - error TS2307: Cannot find module 'types.js' or its corresponding type declarations.
4 import type { GeckodriverParameters } from 'types.js';
```

Add relative path to `types.ts` import

---

package.json

Partial fix to the issue https://github.com/webdriverio-community/node-geckodriver/issues/123. With it [in place](https://github.com/marcin-wosinek/geckodriver-test/tree/main/fix), the bin script still fails, but with another error:
```
$ npx geckodriver --port=4444
node:internal/errors:490
ErrorCaptureStackTrace(err);
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/marcinwosinek/workspace/geckodriver-test/fix/node_modules/geckodriver/dist/cli.js' imported from /Users/marcinwosinek/workspace/geckodriver-test/fix/node_modules/geckodriver/bin/geckodriver.js
at new NodeError (node:internal/errors:399:5)
at finalizeResolution (node:internal/modules/esm/resolve:326:11)
at moduleResolve (node:internal/modules/esm/resolve:945:10)
at defaultResolve …
```

Update the bin-script reference

---

src/index.ts
src/types.ts

There is an undocumented argument (`--websocket-port`) to pass to `geckodriver`, according to https://github.com/mozilla/geckodriver/issues/2011#issuecomment-1121983657
This change documents it and sets it to random (port zero) for new sessions.
Previously if none was set, the default (9222) would be used.
This would pose an issue when users specified `webSocketUrl` capability as N instances running in parallel would try to connect to the default port and fail.
Allows for WebDriver BiDi / CDP - enabled parallel runs for Firefox with the [webdriverIO](https://github.com/webdriverio/webdriverio) project.
Fixes https://github.com/webdriverio/webdriverio/issues/10839

drivers: Document websocket-port arg, set it to random

---

package-lock.json
package.json
src/index.ts
tests/test.e2e.js

WHAT?
Destructured `customGeckoDriverPath` out of `params` in `function start()`.
Additionally, updated `test.e2e.js` to test the three `webdriver` usage modes: 1/ automatically download and start, 2/ automatically start, 3/ manually start.
Finally, added a self-referencing `devDependency` to `geckodriver` since `webdriverio` transitively depends on it.
WHY?
Before this change, running the following code:
```ts
import { start } from 'geckodriver'
await start({ customGeckoDriverPath: '/some/path/geckodriver' })
```
Would fail to start the `geckodriver` because it would execute:
```shell
geckodriver --custom-gecko-driver-path=/some/path/geckodriver --port=43083 --host=0.0.0.0 --websocket-port=0
```
Which results in exit code `64` and the following output:
```log
/some/path/geckodriver: …
```

Fix bug when specifying customGeckoDriverPath

---

src/install.ts

The readme states that
> By default, this package downloads Geckodriver when used for the first time through the CLI or the programmatic interface. If you like to download it as part of the NPM install process, set the GECKODRIVER_AUTO_INSTALL environment flag, e.g.:
However, `Boolean(process.env.GECKODRIVER_AUTO_INSTALL || '1')` will always be `true` regardless of the `GECKODRIVER_AUTO_INSTALL` variable, meaning it will always download the driver during installation process.
This PR fixes the env var detection

Fix installer not respecting GECKODRIVER_AUTO_INSTALL variable

---

src/index.ts

`./geckodriver: error: the argument '--websocket-port <PORT>' cannot be used with '--connect-existing'`
If connectExisting and websocketPort passed same time to geckodriver cause crash because driver can't initialize websocket socket on existing browser
It's a minimal fix. I'm open to typo commits or other suggestions

when if connectExisting passed to driver then args shouldn't include websocketPort

---

README.md
src/index.ts
src/types.ts
tests/start-unit.test.ts

I am currently migrating Cypress to use `webdriver` and `geckodriver` for our firefox automation. We have the needs to propagate some environment variables to the geckodriver process (better outlined in this bugzilla [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1604723#c20)), which we are patching this package to accomplish now. This PR is to move this patch upstream as a contribution.
In order to propagate environment variables to the firefox process started with `geckodriver`, the environment variables need to be passed to the `geckodriver` process directly in order to be passed to `firefox`. This is important for setting `MOZ_` prefixed variables, like `MOZ_HEADLESS_HEIGHT` or `MOZ_HEADLESS_WIDTH`. This PR allows spawn options to be passed into the geckodriver process.

feat: support spawnOpts for geckodriver child process

---

package.json

The previous prepare script used `husky install`, which is deprecated in Husky 9. Updated to use `husky` as recommended.
This will fix the depreciation warnings like in this CI build: https://github.com/webdriverio-community/node-geckodriver/actions/runs/15976775551/job/45061223970#step:4:14

chore: update prepare script for Husky 9 compatibility

---

package-lock.json
package.json
src/install.ts
src/utils.ts
tests/unit.test.ts

BREAKING CHANGE: Node.js 20 or higher is now required. Node.js 18 reached end-of-life in April 2025.
Replace node-fetch with the built-in fetch API available in Node.js 20+. This reduces bundle size and avoids deprecation warnings related to node-domexception. node-fetch hasn't seen much active development lately, and the built-in fetch API makes it largely redundant.
Verified by successful CI workflow run: https://github.com/YasharF/node-geckodriver/actions/runs/16865975050

refactor!: remove node-fetch; require Node.js >=20

---

src/install.ts

- closes https://github.com/webdriverio-community/node-geckodriver/issues/653
The [README > Installing section](https://github.com/webdriverio-community/node-geckodriver/blob/main/README.md#installing) describes how the environment variable `GECKODRIVER_AUTO_INSTALL` can be set to `1` to request that Geckodriver is installed during dependency installation through a package manager such as npm.
This does not work in a Microsoft Windows environment. Executing `npm install geckodriver` with the above environment variable set does not cause Geckodriver to be downloaded.
The check for the calling JavaScript filename `/dist/install.js` in [src/install.ts](https://github.com/webdriverio-community/node-geckodriver/blob/main/src/install.ts) assumes POSIX style paths with forward slash (`/`) …

fix: enable GECKODRIVER_AUTO_INSTALL usage on Windows

---

package-lock.json

Although running `npm ci` executes without error, which usually means that the [package-lock.json](https://github.com/webdriverio-community/node-geckodriver/blob/main/package-lock.json) is fully up-to-date,  if `npm install` is executed, it removes the `dev` key from the active `geckodriver@6.0.1` entry in [package-lock.json](https://github.com/webdriverio-community/node-geckodriver/blob/main/package-lock.json):
```text
$ git diff
diff --git a/package-lock.json b/package-lock.json
index 3729db4..17c9e5b 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -8,7 +8,6 @@
"": {
"name": "geckodriver",
"version": "6.0.1",
-      "dev": true,
"hasInstallScript": true,
"license": "MIT",
"dependencies": {
```
The fact that npm put the `dev` key into this entry in PR …

chore: resync lockfile after geckodriver 5.0.0 dev addition
